# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
      - main
      - release-**

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: cd src
    - run: npm run build --if-present
    - run: npm i
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Zip release package
      run: zip -r test-pulumi-${{ steps.extract_branch.outputs.branch }}.zip .
      if: contains( steps.extract_branch.outputs.branch, 'release' )
    - name: Zip dev package
      run: zip -r test-pulumi.zip .
      if: contains( steps.extract_branch.outputs.branch, 'main' )  
    - run: zip -r test-pulumi-${{ steps.extract_branch.outputs.branch }}.zip .
    - run: cd -
    - run: cd pulumi
    - uses: pulumi/actions@v3
      with:
        command: preview
        stack-name: dev
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
