# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
      - main
      - release-**

jobs:
  build:
    name: Preview
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - run: npm i
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Zip release package
      if: contains( steps.extract_branch.outputs.branch, 'release' )
      run: zip -r test-pulumi-${{ steps.extract_branch.outputs.branch }}.zip .
    - name: Zip dev package
      if: contains( steps.extract_branch.outputs.branch, 'main' )  
      run: zip -r test-pulumi.zip .
    - uses: pulumi/actions@v3
      with:
        command: preview
        stack-name: dev
          
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v2
#       with:
#         node-version: 14.x
#     - run: npm i
#     - name: Extract branch name
#       shell: bash
#       run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
#       id: extract_branch
#     - name: Zip release package
#       if: contains( steps.extract_branch.outputs.branch, 'release' )
#       run: zip -r test-pulumi-${{ steps.extract_branch.outputs.branch }}.zip .
#     - name: Zip dev package
#       if: contains( steps.extract_branch.outputs.branch, 'main' )  
#       run: zip -r test-pulumi.zip .
#     - uses: pulumi/actions@v3
#       with:
#         command: preview
#         stack-name: dev
#       env:
#         PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
